/**
 * Comprehensive pathology test catalog — 160+ tests
 *
 * Sources cross-referenced:
 *   - ICMR (Indian Council of Medical Research) Reference Intervals
 *   - NABL Accreditation Guidelines (ISO 15189)
 *   - Tietz Fundamentals of Clinical Chemistry (8th ed.)
 *   - Harrison's Principles of Internal Medicine (21st ed.)
 *   - Lal PathLabs / Metropolis / Thyrocare / Apollo Diagnostics catalogs
 *   - WHO reference ranges (India-adapted)
 *
 * Hierarchy: Panel tests list child short_codes in reference_range as "See: HB, TLC, ..."
 * Prices: Indicative MRP (2025 INR), editable by lab admin
 *
 * Reference ranges are for adults (18–60 yr) unless noted.
 * Gender-specific: "(M)" = male, "(F)" = female
 */
export const SEED_TESTS = [

  // ══════════════════════════════════════════════════════════════
  // HAEMATOLOGY — CBC PANEL + COMPONENTS
  // ══════════════════════════════════════════════════════════════
  {
    name: "Complete Blood Count (CBC with Differential)",
    short_code: "CBC",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "Panel: HB, RBC, TLC, PLT, PCV, MCV, MCH, MCHC, RDW, DLC",
    unit: "Panel",
    price: 280,
    turnaround_hrs: 4,
  },
  {
    name: "Haemoglobin",
    short_code: "HB",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "13.0–17.5 (M) / 11.5–15.5 (F) / 11.0–14.0 (Child 6–12 yr)",
    unit: "g/dL",
    price: 80,
    turnaround_hrs: 2,
  },
  {
    name: "Red Blood Cell Count",
    short_code: "RBC",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "4.5–5.9 (M) / 3.8–5.2 (F)",
    unit: "million/µL",
    price: 70,
    turnaround_hrs: 2,
  },
  {
    name: "Total Leucocyte Count (WBC)",
    short_code: "TLC",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "4.0–11.0",
    unit: "×10³/µL",
    price: 70,
    turnaround_hrs: 2,
  },
  {
    name: "Platelet Count",
    short_code: "PLT",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "150–400",
    unit: "×10³/µL",
    price: 70,
    turnaround_hrs: 2,
  },
  {
    name: "Packed Cell Volume / Haematocrit",
    short_code: "PCV",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "40–52 (M) / 36–48 (F)",
    unit: "%",
    price: 70,
    turnaround_hrs: 2,
  },
  {
    name: "Mean Corpuscular Volume",
    short_code: "MCV",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "80–100",
    unit: "fL",
    price: 70,
    turnaround_hrs: 2,
  },
  {
    name: "Mean Corpuscular Haemoglobin",
    short_code: "MCH",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "27–33",
    unit: "pg",
    price: 70,
    turnaround_hrs: 2,
  },
  {
    name: "Mean Corpuscular Haemoglobin Concentration",
    short_code: "MCHC",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "31.5–36.0",
    unit: "g/dL",
    price: 70,
    turnaround_hrs: 2,
  },
  {
    name: "RBC Distribution Width",
    short_code: "RDW",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "11.5–14.5",
    unit: "%",
    price: 70,
    turnaround_hrs: 2,
  },
  {
    name: "Differential Leucocyte Count",
    short_code: "DLC",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "Neut 40–70% | Lymph 20–40% | Mono 2–8% | Eos 1–4% | Baso 0–1%",
    unit: "%",
    price: 100,
    turnaround_hrs: 3,
  },
  {
    name: "Absolute Neutrophil Count",
    short_code: "ANC",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "1.8–7.7",
    unit: "×10³/µL",
    price: 100,
    turnaround_hrs: 3,
  },
  {
    name: "Absolute Lymphocyte Count",
    short_code: "ALC",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "1.0–4.8",
    unit: "×10³/µL",
    price: 100,
    turnaround_hrs: 3,
  },
  {
    name: "Erythrocyte Sedimentation Rate",
    short_code: "ESR",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "0–15 (M) / 0–20 (F) — Westergren method",
    unit: "mm/hr",
    price: 80,
    turnaround_hrs: 2,
  },
  {
    name: "Peripheral Blood Smear",
    short_code: "PBS",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "Normocytic normochromic RBCs; no abnormal cells or parasites seen",
    unit: "Qualitative",
    price: 150,
    turnaround_hrs: 4,
  },
  {
    name: "Reticulocyte Count",
    short_code: "RETIC",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "0.5–2.5",
    unit: "%",
    price: 120,
    turnaround_hrs: 4,
  },
  {
    name: "Mean Platelet Volume",
    short_code: "MPV",
    category: "Haematology",
    sample_type: "Blood (EDTA)",
    reference_range: "7.5–12.5",
    unit: "fL",
    price: 70,
    turnaround_hrs: 2,
  },

  // ══════════════════════════════════════════════════════════════
  // LIVER FUNCTION TESTS (LFT PANEL)
  // ══════════════════════════════════════════════════════════════
  {
    name: "Liver Function Test Panel",
    short_code: "LFT",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "Panel: T-BIL, D-BIL, I-BIL, ALT, AST, ALP, GGT, TP, ALB, GLOB, AG-RAT",
    unit: "Panel",
    price: 550,
    turnaround_hrs: 6,
  },
  {
    name: "Total Bilirubin",
    short_code: "T-BIL",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "0.2–1.2",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "Direct Bilirubin (Conjugated)",
    short_code: "D-BIL",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "0.0–0.3",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "Indirect Bilirubin (Unconjugated)",
    short_code: "I-BIL",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "0.1–0.9",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "Alanine Aminotransferase (SGPT/ALT)",
    short_code: "ALT",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "7–56 (M) / 7–40 (F)",
    unit: "U/L",
    price: 100,
    turnaround_hrs: 4,
  },
  {
    name: "Aspartate Aminotransferase (SGOT/AST)",
    short_code: "AST",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "10–40 (M) / 10–35 (F)",
    unit: "U/L",
    price: 100,
    turnaround_hrs: 4,
  },
  {
    name: "Alkaline Phosphatase",
    short_code: "ALP",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "40–130 (adult) / up to 350 (child/adolescent)",
    unit: "U/L",
    price: 100,
    turnaround_hrs: 4,
  },
  {
    name: "Gamma-Glutamyl Transferase",
    short_code: "GGT",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "12–64 (M) / 9–36 (F)",
    unit: "U/L",
    price: 150,
    turnaround_hrs: 4,
  },
  {
    name: "Total Protein",
    short_code: "TP",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "6.0–8.3",
    unit: "g/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "Serum Albumin",
    short_code: "ALB",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "3.5–5.2",
    unit: "g/dL",
    price: 100,
    turnaround_hrs: 4,
  },
  {
    name: "Serum Globulin",
    short_code: "GLOB",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "2.0–3.5",
    unit: "g/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "Albumin/Globulin Ratio",
    short_code: "AG-RAT",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "1.2–2.2",
    unit: "ratio",
    price: 60,
    turnaround_hrs: 4,
  },
  {
    name: "5′-Nucleotidase",
    short_code: "5NT",
    category: "Liver Function",
    sample_type: "Serum",
    reference_range: "2–17",
    unit: "U/L",
    price: 400,
    turnaround_hrs: 8,
  },

  // ══════════════════════════════════════════════════════════════
  // KIDNEY / RENAL FUNCTION TESTS (KFT PANEL)
  // ══════════════════════════════════════════════════════════════
  {
    name: "Kidney Function Test Panel",
    short_code: "KFT",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "Panel: SCREAT, UREA, BUN, SUA, NA, K, CL, CA, PHOS, EGFR",
    unit: "Panel",
    price: 550,
    turnaround_hrs: 6,
  },
  {
    name: "Serum Creatinine",
    short_code: "SCREAT",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "0.7–1.3 (M) / 0.5–1.1 (F)",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 3,
  },
  {
    name: "Serum Urea",
    short_code: "UREA",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "15–45",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 3,
  },
  {
    name: "Blood Urea Nitrogen",
    short_code: "BUN",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "7–20",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 3,
  },
  {
    name: "Serum Uric Acid",
    short_code: "SUA",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "3.5–7.2 (M) / 2.6–6.0 (F)",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 3,
  },
  {
    name: "eGFR (CKD-EPI)",
    short_code: "EGFR",
    category: "Kidney Function",
    sample_type: "Serum (calculated)",
    reference_range: "≥60 (normal kidney function)",
    unit: "mL/min/1.73m²",
    price: 60,
    turnaround_hrs: 3,
  },
  {
    name: "Serum Sodium",
    short_code: "NA",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "136–145",
    unit: "mEq/L",
    price: 120,
    turnaround_hrs: 3,
  },
  {
    name: "Serum Potassium",
    short_code: "K",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "3.5–5.1",
    unit: "mEq/L",
    price: 120,
    turnaround_hrs: 3,
  },
  {
    name: "Serum Chloride",
    short_code: "CL",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "98–107",
    unit: "mEq/L",
    price: 100,
    turnaround_hrs: 3,
  },
  {
    name: "Serum Calcium (Total)",
    short_code: "CA",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "8.6–10.3",
    unit: "mg/dL",
    price: 100,
    turnaround_hrs: 3,
  },
  {
    name: "Serum Phosphorus (Inorganic)",
    short_code: "PHOS",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "2.5–4.5",
    unit: "mg/dL",
    price: 100,
    turnaround_hrs: 3,
  },
  {
    name: "Serum Magnesium",
    short_code: "MG",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "1.7–2.4",
    unit: "mg/dL",
    price: 150,
    turnaround_hrs: 4,
  },
  {
    name: "Serum Bicarbonate (CO₂)",
    short_code: "HCO3",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "22–29",
    unit: "mEq/L",
    price: 100,
    turnaround_hrs: 3,
  },
  {
    name: "Cystatin C",
    short_code: "CYS-C",
    category: "Kidney Function",
    sample_type: "Serum",
    reference_range: "0.52–0.98",
    unit: "mg/L",
    price: 1200,
    turnaround_hrs: 12,
  },

  // ══════════════════════════════════════════════════════════════
  // LIPID PROFILE PANEL
  // ══════════════════════════════════════════════════════════════
  {
    name: "Lipid Profile Panel",
    short_code: "LP",
    category: "Lipid Profile",
    sample_type: "Serum (fasting 10–12 hr)",
    reference_range: "Panel: TC, HDL-C, LDL-C, VLDL-C, TG, TC-HDL-RAT",
    unit: "Panel",
    price: 450,
    turnaround_hrs: 6,
  },
  {
    name: "Total Cholesterol",
    short_code: "TC",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "Desirable <200 / Borderline 200–239 / High ≥240",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "HDL Cholesterol (Good Cholesterol)",
    short_code: "HDL-C",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "≥40 (M) / ≥50 (F) — Low risk >60",
    unit: "mg/dL",
    price: 100,
    turnaround_hrs: 4,
  },
  {
    name: "LDL Cholesterol (Calculated)",
    short_code: "LDL-C",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "Optimal <100 / Near optimal 100–129 / High ≥160",
    unit: "mg/dL",
    price: 100,
    turnaround_hrs: 4,
  },
  {
    name: "VLDL Cholesterol (Calculated)",
    short_code: "VLDL-C",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "2–30",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "Triglycerides",
    short_code: "TG",
    category: "Lipid Profile",
    sample_type: "Serum (fasting)",
    reference_range: "Normal <150 / Borderline 150–199 / High ≥200",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "Total Cholesterol / HDL Ratio",
    short_code: "TC-HDL-RAT",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "<5.0 (desirable)",
    unit: "ratio",
    price: 60,
    turnaround_hrs: 4,
  },
  {
    name: "Non-HDL Cholesterol",
    short_code: "NON-HDL",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "<130",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 4,
  },
  {
    name: "Lipoprotein (a)",
    short_code: "LPA",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "<30",
    unit: "mg/dL",
    price: 900,
    turnaround_hrs: 12,
  },
  {
    name: "ApolipoproteinA1",
    short_code: "APOA1",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "119–240 (M) / 116–209 (F)",
    unit: "mg/dL",
    price: 700,
    turnaround_hrs: 8,
  },
  {
    name: "Apolipoprotein B",
    short_code: "APOB",
    category: "Lipid Profile",
    sample_type: "Serum",
    reference_range: "52–163 (M) / 49–174 (F)",
    unit: "mg/dL",
    price: 700,
    turnaround_hrs: 8,
  },

  // ══════════════════════════════════════════════════════════════
  // THYROID FUNCTION TESTS
  // ══════════════════════════════════════════════════════════════
  {
    name: "Thyroid Profile (T3, T4, TSH)",
    short_code: "TFT",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "Panel: TSH, FT3, FT4, T3, T4",
    unit: "Panel",
    price: 600,
    turnaround_hrs: 8,
  },
  {
    name: "Thyroid Stimulating Hormone (TSH)",
    short_code: "TSH",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "0.27–4.20 (adult) / 0.60–10.0 (neonate)",
    unit: "µIU/mL",
    price: 350,
    turnaround_hrs: 6,
  },
  {
    name: "Free Triiodothyronine (FT3)",
    short_code: "FT3",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "2.0–4.4",
    unit: "pg/mL",
    price: 280,
    turnaround_hrs: 6,
  },
  {
    name: "Free Thyroxine (FT4)",
    short_code: "FT4",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "0.93–1.70",
    unit: "ng/dL",
    price: 280,
    turnaround_hrs: 6,
  },
  {
    name: "Total Triiodothyronine (T3)",
    short_code: "T3",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "80–200",
    unit: "ng/dL",
    price: 220,
    turnaround_hrs: 6,
  },
  {
    name: "Total Thyroxine (T4)",
    short_code: "T4",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "5.1–14.1",
    unit: "µg/dL",
    price: 220,
    turnaround_hrs: 6,
  },
  {
    name: "Anti-Thyroid Peroxidase Antibody (Anti-TPO)",
    short_code: "ANTI-TPO",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "<34",
    unit: "IU/mL",
    price: 550,
    turnaround_hrs: 12,
  },
  {
    name: "Anti-Thyroglobulin Antibody (Anti-TG)",
    short_code: "ANTI-TG",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "<115",
    unit: "IU/mL",
    price: 550,
    turnaround_hrs: 12,
  },
  {
    name: "Thyroglobulin",
    short_code: "TG-AB",
    category: "Thyroid",
    sample_type: "Serum",
    reference_range: "1.4–78.0",
    unit: "ng/mL",
    price: 800,
    turnaround_hrs: 12,
  },

  // ══════════════════════════════════════════════════════════════
  // DIABETES / GLUCOSE
  // ══════════════════════════════════════════════════════════════
  {
    name: "Fasting Blood Glucose (FBG)",
    short_code: "FBG",
    category: "Diabetes",
    sample_type: "Plasma (Fluoride EDTA, fasting ≥8 hr)",
    reference_range: "Normal 70–99 / Pre-diabetic 100–125 / Diabetic ≥126",
    unit: "mg/dL",
    price: 60,
    turnaround_hrs: 2,
  },
  {
    name: "Post-Prandial Blood Glucose (2-hr PPBG)",
    short_code: "PPBG",
    category: "Diabetes",
    sample_type: "Plasma (Fluoride, 2 hr after 75g glucose load)",
    reference_range: "Normal <140 / Pre-diabetic 140–199 / Diabetic ≥200",
    unit: "mg/dL",
    price: 60,
    turnaround_hrs: 2,
  },
  {
    name: "Random Blood Glucose",
    short_code: "RBG",
    category: "Diabetes",
    sample_type: "Plasma (Fluoride)",
    reference_range: "<200 (non-diabetic) / ≥200 with symptoms = Diabetic",
    unit: "mg/dL",
    price: 60,
    turnaround_hrs: 1,
  },
  {
    name: "Glycated Haemoglobin (HbA1c)",
    short_code: "HBAIC",
    category: "Diabetes",
    sample_type: "Blood (EDTA)",
    reference_range: "Non-diabetic <5.7% / Pre-diabetic 5.7–6.4% / Diabetic ≥6.5%",
    unit: "%",
    price: 400,
    turnaround_hrs: 6,
  },
  {
    name: "Fasting Insulin",
    short_code: "INS-F",
    category: "Diabetes",
    sample_type: "Serum (fasting ≥8 hr)",
    reference_range: "2.6–24.9",
    unit: "µIU/mL",
    price: 550,
    turnaround_hrs: 8,
  },
  {
    name: "C-Peptide (Fasting)",
    short_code: "C-PEP",
    category: "Diabetes",
    sample_type: "Serum (fasting)",
    reference_range: "0.8–3.5",
    unit: "ng/mL",
    price: 750,
    turnaround_hrs: 8,
  },
  {
    name: "HOMA-IR (Insulin Resistance Index)",
    short_code: "HOMA",
    category: "Diabetes",
    sample_type: "Calculated from FBG + Fasting Insulin",
    reference_range: "<1.9 (normal) / 1.9–2.9 (early IR) / >2.9 (IR)",
    unit: "index",
    price: 100,
    turnaround_hrs: 8,
  },

  // ══════════════════════════════════════════════════════════════
  // URINE ANALYSIS
  // ══════════════════════════════════════════════════════════════
  {
    name: "Urine Routine Examination",
    short_code: "URE",
    category: "Urine Analysis",
    sample_type: "Urine (mid-stream, morning first void)",
    reference_range: "Colour: pale yellow / pH 4.5–8.5 / SpGrav 1.003–1.030 / Protein Nil / Glucose Nil / RBC 0–2/HPF / WBC 0–5/HPF / Casts Nil",
    unit: "Panel",
    price: 120,
    turnaround_hrs: 2,
  },
  {
    name: "Urine Culture and Sensitivity",
    short_code: "UCS",
    category: "Urine Analysis",
    sample_type: "Urine (mid-stream, clean-catch)",
    reference_range: "<10,000 CFU/mL (no significant growth)",
    unit: "CFU/mL",
    price: 450,
    turnaround_hrs: 48,
  },
  {
    name: "Urine Microalbumin / Creatinine Ratio (ACR)",
    short_code: "U-ACR",
    category: "Urine Analysis",
    sample_type: "Urine (random spot)",
    reference_range: "Normal <30 / Microalbuminuria 30–300 / Macroalbuminuria >300",
    unit: "µg/mg creatinine",
    price: 550,
    turnaround_hrs: 6,
  },
  {
    name: "24-Hour Urine Protein",
    short_code: "24H-UPROT",
    category: "Urine Analysis",
    sample_type: "Urine (24-hour collection)",
    reference_range: "<150",
    unit: "mg/24hr",
    price: 300,
    turnaround_hrs: 6,
  },
  {
    name: "Urine Creatinine (Spot)",
    short_code: "U-CREAT",
    category: "Urine Analysis",
    sample_type: "Urine (random spot)",
    reference_range: "0.7–1.5 (M) / 0.5–1.3 (F)",
    unit: "g/L",
    price: 120,
    turnaround_hrs: 3,
  },
  {
    name: "Urine Sodium (Spot)",
    short_code: "U-NA",
    category: "Urine Analysis",
    sample_type: "Urine (random spot)",
    reference_range: "20–220",
    unit: "mEq/L",
    price: 150,
    turnaround_hrs: 3,
  },
  {
    name: "Urine Pregnancy Test (hCG)",
    short_code: "UPT",
    category: "Urine Analysis",
    sample_type: "Urine (first morning void)",
    reference_range: "Negative (non-pregnant)",
    unit: "Qualitative",
    price: 80,
    turnaround_hrs: 1,
  },

  // ══════════════════════════════════════════════════════════════
  // IRON STUDIES
  // ══════════════════════════════════════════════════════════════
  {
    name: "Iron Studies Panel",
    short_code: "IRON-P",
    category: "Iron Studies",
    sample_type: "Serum (fasting, morning)",
    reference_range: "Panel: S-IRON, TIBC, UIBC, FERR, T-SAT",
    unit: "Panel",
    price: 700,
    turnaround_hrs: 8,
  },
  {
    name: "Serum Iron",
    short_code: "S-IRON",
    category: "Iron Studies",
    sample_type: "Serum (fasting, morning)",
    reference_range: "60–170 (M) / 37–170 (F)",
    unit: "µg/dL",
    price: 200,
    turnaround_hrs: 6,
  },
  {
    name: "Total Iron Binding Capacity (TIBC)",
    short_code: "TIBC",
    category: "Iron Studies",
    sample_type: "Serum",
    reference_range: "250–450",
    unit: "µg/dL",
    price: 200,
    turnaround_hrs: 6,
  },
  {
    name: "Unsaturated Iron Binding Capacity (UIBC)",
    short_code: "UIBC",
    category: "Iron Studies",
    sample_type: "Serum",
    reference_range: "155–355",
    unit: "µg/dL",
    price: 200,
    turnaround_hrs: 6,
  },
  {
    name: "Serum Ferritin",
    short_code: "FERR",
    category: "Iron Studies",
    sample_type: "Serum",
    reference_range: "22–322 (M) / 10–291 (F)",
    unit: "ng/mL",
    price: 650,
    turnaround_hrs: 8,
  },
  {
    name: "Transferrin Saturation",
    short_code: "T-SAT",
    category: "Iron Studies",
    sample_type: "Serum (calculated)",
    reference_range: "20–50",
    unit: "%",
    price: 100,
    turnaround_hrs: 6,
  },

  // ══════════════════════════════════════════════════════════════
  // COAGULATION
  // ══════════════════════════════════════════════════════════════
  {
    name: "Prothrombin Time / INR",
    short_code: "PT-INR",
    category: "Coagulation",
    sample_type: "Plasma (Sodium Citrate 3.2%)",
    reference_range: "PT 11–14 sec / INR 0.8–1.2 (therapeutic target 2.0–3.0)",
    unit: "sec / ratio",
    price: 220,
    turnaround_hrs: 4,
  },
  {
    name: "Activated Partial Thromboplastin Time (aPTT)",
    short_code: "APTT",
    category: "Coagulation",
    sample_type: "Plasma (Sodium Citrate 3.2%)",
    reference_range: "25–38",
    unit: "sec",
    price: 220,
    turnaround_hrs: 4,
  },
  {
    name: "D-Dimer",
    short_code: "D-DIM",
    category: "Coagulation",
    sample_type: "Plasma (Citrate)",
    reference_range: "<0.50",
    unit: "µg/mL FEU",
    price: 850,
    turnaround_hrs: 4,
  },
  {
    name: "Fibrinogen",
    short_code: "FIB",
    category: "Coagulation",
    sample_type: "Plasma (Citrate)",
    reference_range: "200–400",
    unit: "mg/dL",
    price: 550,
    turnaround_hrs: 6,
  },
  {
    name: "Thrombin Time",
    short_code: "TT",
    category: "Coagulation",
    sample_type: "Plasma (Citrate)",
    reference_range: "14–21",
    unit: "sec",
    price: 300,
    turnaround_hrs: 4,
  },
  {
    name: "Bleeding Time",
    short_code: "BT",
    category: "Coagulation",
    sample_type: "Capillary blood (Duke's method)",
    reference_range: "1–5",
    unit: "min",
    price: 100,
    turnaround_hrs: 1,
  },
  {
    name: "Clotting Time",
    short_code: "CT",
    category: "Coagulation",
    sample_type: "Capillary blood",
    reference_range: "5–11",
    unit: "min",
    price: 100,
    turnaround_hrs: 1,
  },

  // ══════════════════════════════════════════════════════════════
  // CARDIAC MARKERS
  // ══════════════════════════════════════════════════════════════
  {
    name: "Troponin I (High Sensitivity, hs-TnI)",
    short_code: "HS-TROP-I",
    category: "Cardiac Markers",
    sample_type: "Serum",
    reference_range: "<16 (M) / <11 (F) [99th percentile URL]",
    unit: "ng/L",
    price: 1300,
    turnaround_hrs: 2,
  },
  {
    name: "Troponin T (High Sensitivity, hs-TnT)",
    short_code: "HS-TROP-T",
    category: "Cardiac Markers",
    sample_type: "Serum",
    reference_range: "<19",
    unit: "ng/L",
    price: 1300,
    turnaround_hrs: 2,
  },
  {
    name: "Creatine Kinase MB (CK-MB)",
    short_code: "CK-MB",
    category: "Cardiac Markers",
    sample_type: "Serum",
    reference_range: "<5.0 (M) / <3.6 (F)",
    unit: "ng/mL",
    price: 550,
    turnaround_hrs: 4,
  },
  {
    name: "Total Creatine Kinase (CK/CPK)",
    short_code: "CK",
    category: "Cardiac Markers",
    sample_type: "Serum",
    reference_range: "38–174 (M) / 26–140 (F)",
    unit: "U/L",
    price: 250,
    turnaround_hrs: 4,
  },
  {
    name: "NT-proBNP",
    short_code: "BNPP",
    category: "Cardiac Markers",
    sample_type: "Serum",
    reference_range: "<125 (age <75 yr) / <450 (age ≥75 yr)",
    unit: "pg/mL",
    price: 2600,
    turnaround_hrs: 6,
  },
  {
    name: "LDH (Lactate Dehydrogenase)",
    short_code: "LDH",
    category: "Cardiac Markers",
    sample_type: "Serum",
    reference_range: "125–220",
    unit: "U/L",
    price: 220,
    turnaround_hrs: 4,
  },
  {
    name: "Myoglobin",
    short_code: "MYO",
    category: "Cardiac Markers",
    sample_type: "Serum",
    reference_range: "16–76 (M) / 7–64 (F)",
    unit: "µg/L",
    price: 600,
    turnaround_hrs: 4,
  },
  {
    name: "Homocysteine",
    short_code: "HOMO",
    category: "Cardiac Markers",
    sample_type: "Plasma (EDTA, fasting)",
    reference_range: "5–15",
    unit: "µmol/L",
    price: 900,
    turnaround_hrs: 12,
  },

  // ══════════════════════════════════════════════════════════════
  // BIOCHEMISTRY / GENERAL
  // ══════════════════════════════════════════════════════════════
  {
    name: "C-Reactive Protein (CRP)",
    short_code: "CRP",
    category: "Biochemistry",
    sample_type: "Serum",
    reference_range: "<6.0",
    unit: "mg/L",
    price: 280,
    turnaround_hrs: 4,
  },
  {
    name: "High Sensitivity CRP (hsCRP)",
    short_code: "HS-CRP",
    category: "Biochemistry",
    sample_type: "Serum",
    reference_range: "Low risk <1.0 / Average 1.0–3.0 / High risk >3.0",
    unit: "mg/L",
    price: 600,
    turnaround_hrs: 6,
  },
  {
    name: "Serum Amylase",
    short_code: "AMY",
    category: "Biochemistry",
    sample_type: "Serum",
    reference_range: "30–110",
    unit: "U/L",
    price: 220,
    turnaround_hrs: 4,
  },
  {
    name: "Serum Lipase",
    short_code: "LPS",
    category: "Biochemistry",
    sample_type: "Serum",
    reference_range: "13–60",
    unit: "U/L",
    price: 380,
    turnaround_hrs: 4,
  },
  {
    name: "Serum Uric Acid",
    short_code: "SUA-B",
    category: "Biochemistry",
    sample_type: "Serum",
    reference_range: "3.5–7.2 (M) / 2.6–6.0 (F)",
    unit: "mg/dL",
    price: 80,
    turnaround_hrs: 3,
  },
  {
    name: "Lactate (Lactic Acid)",
    short_code: "LAC",
    category: "Biochemistry",
    sample_type: "Plasma (Fluoride, arterial/venous)",
    reference_range: "0.5–2.2 (venous)",
    unit: "mmol/L",
    price: 600,
    turnaround_hrs: 2,
  },
  {
    name: "Serum Copper",
    short_code: "CU",
    category: "Biochemistry",
    sample_type: "Serum",
    reference_range: "70–150 (M) / 80–155 (F)",
    unit: "µg/dL",
    price: 800,
    turnaround_hrs: 24,
  },
  {
    name: "Serum Zinc",
    short_code: "ZN",
    category: "Biochemistry",
    sample_type: "Serum (fasting)",
    reference_range: "70–120",
    unit: "µg/dL",
    price: 800,
    turnaround_hrs: 24,
  },

  // ══════════════════════════════════════════════════════════════
  // VITAMINS & MINERALS
  // ══════════════════════════════════════════════════════════════
  {
    name: "25-Hydroxy Vitamin D (Vit D3)",
    short_code: "VIT-D",
    category: "Vitamins & Minerals",
    sample_type: "Serum",
    reference_range: "Deficient <20 / Insufficient 20–29 / Sufficient 30–100",
    unit: "ng/mL",
    price: 1100,
    turnaround_hrs: 12,
  },
  {
    name: "Vitamin B12 (Cobalamin)",
    short_code: "VIT-B12",
    category: "Vitamins & Minerals",
    sample_type: "Serum",
    reference_range: "160–950",
    unit: "pg/mL",
    price: 750,
    turnaround_hrs: 12,
  },
  {
    name: "Folic Acid (Vitamin B9)",
    short_code: "FOL",
    category: "Vitamins & Minerals",
    sample_type: "Serum",
    reference_range: "3.0–20.0",
    unit: "ng/mL",
    price: 650,
    turnaround_hrs: 12,
  },
  {
    name: "Vitamin B6 (Pyridoxine)",
    short_code: "VIT-B6",
    category: "Vitamins & Minerals",
    sample_type: "Plasma (EDTA)",
    reference_range: "5–50",
    unit: "nmol/L",
    price: 1500,
    turnaround_hrs: 24,
  },
  {
    name: "Vitamin A (Retinol)",
    short_code: "VIT-A",
    category: "Vitamins & Minerals",
    sample_type: "Serum (fasting, protect from light)",
    reference_range: "0.30–0.70",
    unit: "mg/L",
    price: 1300,
    turnaround_hrs: 24,
  },
  {
    name: "Vitamin C (Ascorbic Acid)",
    short_code: "VIT-C",
    category: "Vitamins & Minerals",
    sample_type: "Plasma (Oxalate, protect from light)",
    reference_range: "0.4–1.5",
    unit: "mg/dL",
    price: 1200,
    turnaround_hrs: 24,
  },
  {
    name: "Vitamin E (Alpha-Tocopherol)",
    short_code: "VIT-E",
    category: "Vitamins & Minerals",
    sample_type: "Serum (protect from light)",
    reference_range: "5.5–17.0",
    unit: "mg/L",
    price: 1500,
    turnaround_hrs: 24,
  },

  // ══════════════════════════════════════════════════════════════
  // HORMONES
  // ══════════════════════════════════════════════════════════════
  {
    name: "Testosterone (Total)",
    short_code: "TEST",
    category: "Hormones",
    sample_type: "Serum (8–10 AM)",
    reference_range: "2.49–8.36 (M) / 0.08–0.60 (F)",
    unit: "ng/mL",
    price: 650,
    turnaround_hrs: 8,
  },
  {
    name: "Free Testosterone",
    short_code: "FREE-TEST",
    category: "Hormones",
    sample_type: "Serum (8–10 AM)",
    reference_range: "8.7–25.1 (M) / 0.06–1.68 (F)",
    unit: "pg/mL",
    price: 900,
    turnaround_hrs: 12,
  },
  {
    name: "Estradiol (E2)",
    short_code: "E2",
    category: "Hormones",
    sample_type: "Serum",
    reference_range: "Follicular 12–166 / Luteal 44–411 / Postmenopausal <6–54 / (M) 7.6–42.6",
    unit: "pg/mL",
    price: 750,
    turnaround_hrs: 8,
  },
  {
    name: "Follicle Stimulating Hormone (FSH)",
    short_code: "FSH",
    category: "Hormones",
    sample_type: "Serum",
    reference_range: "(F) Follicular 3.0–10.6 / Luteal 1.5–7.4 / Postmeno 26–135 / (M) 1.5–12.4",
    unit: "mIU/mL",
    price: 550,
    turnaround_hrs: 8,
  },
  {
    name: "Luteinizing Hormone (LH)",
    short_code: "LH",
    category: "Hormones",
    sample_type: "Serum",
    reference_range: "(F) Follicular 2.4–12.6 / Luteal 1.0–11.4 / Postmeno 7.7–58.5 / (M) 1.7–8.6",
    unit: "mIU/mL",
    price: 550,
    turnaround_hrs: 8,
  },
  {
    name: "Prolactin",
    short_code: "PRL",
    category: "Hormones",
    sample_type: "Serum (morning, fasting, non-stressed)",
    reference_range: "4.8–23.3 (F non-pregnant) / 4.0–15.2 (M)",
    unit: "ng/mL",
    price: 550,
    turnaround_hrs: 8,
  },
  {
    name: "Anti-Müllerian Hormone (AMH)",
    short_code: "AMH",
    category: "Hormones",
    sample_type: "Serum",
    reference_range: "1.0–3.5 (optimal fertility) / <0.5 (low ovarian reserve)",
    unit: "ng/mL",
    price: 1900,
    turnaround_hrs: 24,
  },
  {
    name: "Cortisol (Morning)",
    short_code: "CORT",
    category: "Hormones",
    sample_type: "Serum (8–9 AM)",
    reference_range: "6.2–19.4",
    unit: "µg/dL",
    price: 650,
    turnaround_hrs: 8,
  },
  {
    name: "DHEA-Sulphate (DHEAS)",
    short_code: "DHEAS",
    category: "Hormones",
    sample_type: "Serum",
    reference_range: "80–560 (M 19–55 yr) / 35–430 (F 19–55 yr)",
    unit: "µg/dL",
    price: 750,
    turnaround_hrs: 8,
  },
  {
    name: "Progesterone",
    short_code: "PROG",
    category: "Hormones",
    sample_type: "Serum",
    reference_range: "Follicular 0.1–0.7 / Luteal 2.0–25.0 / Postmeno <0.1 / (M) 0.3–1.2",
    unit: "ng/mL",
    price: 600,
    turnaround_hrs: 8,
  },
  {
    name: "Sex Hormone Binding Globulin (SHBG)",
    short_code: "SHBG",
    category: "Hormones",
    sample_type: "Serum",
    reference_range: "16.5–55.9 (M) / 24.6–122.0 (F premenopause)",
    unit: "nmol/L",
    price: 800,
    turnaround_hrs: 12,
  },
  {
    name: "Growth Hormone (GH)",
    short_code: "GH",
    category: "Hormones",
    sample_type: "Serum (fasting, rest 30 min)",
    reference_range: "<1.0 (adult basal)",
    unit: "ng/mL",
    price: 900,
    turnaround_hrs: 12,
  },
  {
    name: "Insulin-like Growth Factor 1 (IGF-1)",
    short_code: "IGF1",
    category: "Hormones",
    sample_type: "Serum",
    reference_range: "115–307 (adult 18–30 yr) / 94–252 (31–50 yr)",
    unit: "ng/mL",
    price: 1500,
    turnaround_hrs: 24,
  },
  {
    name: "Parathyroid Hormone (PTH, intact)",
    short_code: "PTH",
    category: "Hormones",
    sample_type: "Plasma (EDTA, on ice)",
    reference_range: "18–88",
    unit: "pg/mL",
    price: 1200,
    turnaround_hrs: 12,
  },
  {
    name: "Aldosterone (Seated)",
    short_code: "ALDO",
    category: "Hormones",
    sample_type: "Serum (seated 30 min)",
    reference_range: "4–31",
    unit: "ng/dL",
    price: 1200,
    turnaround_hrs: 24,
  },
  {
    name: "Renin Activity (Plasma Renin Activity)",
    short_code: "PRA",
    category: "Hormones",
    sample_type: "Plasma (EDTA, on ice)",
    reference_range: "0.2–3.3 (seated)",
    unit: "ng/mL/hr",
    price: 1800,
    turnaround_hrs: 24,
  },

  // ══════════════════════════════════════════════════════════════
  // TUMOR MARKERS
  // ══════════════════════════════════════════════════════════════
  {
    name: "Prostate Specific Antigen (Total PSA)",
    short_code: "PSA",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<4.0 (general) / 40–49 yr <2.5 / 50–59 yr <3.5 / 60–69 yr <4.5",
    unit: "ng/mL",
    price: 650,
    turnaround_hrs: 8,
  },
  {
    name: "Free PSA / Total PSA Ratio",
    short_code: "F-PSA",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: ">25% (low cancer risk) / <10% (high cancer risk)",
    unit: "%",
    price: 800,
    turnaround_hrs: 8,
  },
  {
    name: "Alpha-Fetoprotein (AFP)",
    short_code: "AFP",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<10",
    unit: "ng/mL",
    price: 850,
    turnaround_hrs: 8,
  },
  {
    name: "Carcinoembryonic Antigen (CEA)",
    short_code: "CEA",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<2.5 (non-smoker) / <5.0 (smoker)",
    unit: "ng/mL",
    price: 750,
    turnaround_hrs: 8,
  },
  {
    name: "CA 125 (Ovarian Cancer Marker)",
    short_code: "CA125",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<35",
    unit: "U/mL",
    price: 850,
    turnaround_hrs: 8,
  },
  {
    name: "CA 19-9 (Pancreatic/GI Marker)",
    short_code: "CA199",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<37",
    unit: "U/mL",
    price: 950,
    turnaround_hrs: 8,
  },
  {
    name: "CA 15-3 (Breast Cancer Marker)",
    short_code: "CA153",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<30",
    unit: "U/mL",
    price: 950,
    turnaround_hrs: 8,
  },
  {
    name: "CA 72-4 (Gastric Marker)",
    short_code: "CA724",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<6.9",
    unit: "U/mL",
    price: 1100,
    turnaround_hrs: 12,
  },
  {
    name: "β-hCG (Beta Human Chorionic Gonadotropin)",
    short_code: "BHCG",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<5 (non-pregnant M & F)",
    unit: "mIU/mL",
    price: 650,
    turnaround_hrs: 6,
  },
  {
    name: "NSE (Neuron-Specific Enolase)",
    short_code: "NSE",
    category: "Tumor Markers",
    sample_type: "Serum",
    reference_range: "<16.3",
    unit: "ng/mL",
    price: 1200,
    turnaround_hrs: 12,
  },

  // ══════════════════════════════════════════════════════════════
  // INFECTIOUS DISEASE SEROLOGY
  // ══════════════════════════════════════════════════════════════
  {
    name: "HIV 1 & 2 Antigen/Antibody (4th Generation)",
    short_code: "HIV",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 350,
    turnaround_hrs: 6,
  },
  {
    name: "Hepatitis B Surface Antigen (HBsAg)",
    short_code: "HBSAG",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 280,
    turnaround_hrs: 4,
  },
  {
    name: "Hepatitis B Core Antibody IgM (Anti-HBc IgM)",
    short_code: "ANTI-HBC",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 550,
    turnaround_hrs: 6,
  },
  {
    name: "Hepatitis B e-Antigen (HBeAg)",
    short_code: "HBEAG",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 550,
    turnaround_hrs: 6,
  },
  {
    name: "Hepatitis B Surface Antibody (Anti-HBs)",
    short_code: "ANTI-HBS",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Protected ≥10 / Negative <10",
    unit: "mIU/mL",
    price: 400,
    turnaround_hrs: 6,
  },
  {
    name: "Hepatitis C Antibody (Anti-HCV)",
    short_code: "ANTI-HCV",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 450,
    turnaround_hrs: 6,
  },
  {
    name: "VDRL Test (Syphilis Screening)",
    short_code: "VDRL",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Titer",
    price: 160,
    turnaround_hrs: 4,
  },
  {
    name: "TPHA (Syphilis Confirmatory)",
    short_code: "TPHA",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 350,
    turnaround_hrs: 6,
  },
  {
    name: "Widal Test (Typhoid Serology)",
    short_code: "WIDAL",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "O antigen <1:80 / H antigen <1:160 (single sample interpretation limited)",
    unit: "Titer",
    price: 160,
    turnaround_hrs: 4,
  },
  {
    name: "Malaria Parasite (Peripheral Smear)",
    short_code: "MP",
    category: "Infectious Disease",
    sample_type: "Blood (thick + thin smear, EDTA)",
    reference_range: "No malarial parasites seen",
    unit: "Qualitative",
    price: 130,
    turnaround_hrs: 3,
  },
  {
    name: "Malaria Rapid Antigen Test (PfPv)",
    short_code: "MRDT",
    category: "Infectious Disease",
    sample_type: "Blood (EDTA)",
    reference_range: "Negative (P.falciparum & P.vivax)",
    unit: "Qualitative",
    price: 220,
    turnaround_hrs: 1,
  },
  {
    name: "Dengue NS1 Antigen",
    short_code: "DENG-NS1",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 550,
    turnaround_hrs: 4,
  },
  {
    name: "Dengue IgM/IgG Antibody",
    short_code: "DENG-AB",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 750,
    turnaround_hrs: 6,
  },
  {
    name: "Typhoid IgM (Rapid/Widal)",
    short_code: "TYPHI-IG",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 280,
    turnaround_hrs: 2,
  },
  {
    name: "Leptospira IgM (MAT)",
    short_code: "LEPTO",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Titer <1:20 (Non-Reactive)",
    unit: "Titer",
    price: 700,
    turnaround_hrs: 12,
  },
  {
    name: "Scrub Typhus IgM",
    short_code: "SCRUB-IGM",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Negative",
    unit: "Qualitative",
    price: 700,
    turnaround_hrs: 12,
  },
  {
    name: "COVID-19 Antigen Rapid Test",
    short_code: "COVID-AG",
    category: "Infectious Disease",
    sample_type: "Nasopharyngeal swab",
    reference_range: "Negative",
    unit: "Qualitative",
    price: 300,
    turnaround_hrs: 1,
  },
  {
    name: "COVID-19 IgG Antibody (Post-infection/Vaccination)",
    short_code: "COVID-IGG",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Protective >50 AU/mL (varies by assay)",
    unit: "AU/mL",
    price: 700,
    turnaround_hrs: 6,
  },
  {
    name: "Toxoplasma IgM",
    short_code: "TOXO-IGM",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Negative",
    unit: "Qualitative",
    price: 700,
    turnaround_hrs: 8,
  },
  {
    name: "Rubella IgG / IgM",
    short_code: "RUBELLA",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "IgG: Protected >10 IU/mL / IgM: Negative",
    unit: "IU/mL / Qualitative",
    price: 700,
    turnaround_hrs: 8,
  },
  {
    name: "CMV IgG / IgM",
    short_code: "CMV",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "IgM: Non-Reactive / IgG: varies (positive = past exposure)",
    unit: "Qualitative",
    price: 750,
    turnaround_hrs: 8,
  },
  {
    name: "Herpes Simplex Virus IgM (HSV 1&2)",
    short_code: "HSV",
    category: "Infectious Disease",
    sample_type: "Serum",
    reference_range: "Non-Reactive",
    unit: "Qualitative",
    price: 700,
    turnaround_hrs: 8,
  },

  // ══════════════════════════════════════════════════════════════
  // AUTOIMMUNE / IMMUNOLOGY
  // ══════════════════════════════════════════════════════════════
  {
    name: "Antinuclear Antibody (ANA) by IFA",
    short_code: "ANA",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "Negative (<1:40 by IFA)",
    unit: "Titer",
    price: 950,
    turnaround_hrs: 24,
  },
  {
    name: "Anti-dsDNA Antibody",
    short_code: "ANTI-DSDNA",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "<30",
    unit: "IU/mL",
    price: 1100,
    turnaround_hrs: 24,
  },
  {
    name: "Rheumatoid Factor (RF)",
    short_code: "RF",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "<14",
    unit: "IU/mL",
    price: 250,
    turnaround_hrs: 6,
  },
  {
    name: "Anti-CCP Antibody (Anti-Cyclic Citrullinated Peptide)",
    short_code: "ANTI-CCP",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "<5",
    unit: "U/mL",
    price: 1000,
    turnaround_hrs: 12,
  },
  {
    name: "Complement C3",
    short_code: "C3",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "90–180",
    unit: "mg/dL",
    price: 700,
    turnaround_hrs: 8,
  },
  {
    name: "Complement C4",
    short_code: "C4",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "16–47",
    unit: "mg/dL",
    price: 700,
    turnaround_hrs: 8,
  },
  {
    name: "IgE (Total Immunoglobulin E)",
    short_code: "IGE",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "<100 (adult) / <200 (atopic individuals may be higher)",
    unit: "IU/mL",
    price: 700,
    turnaround_hrs: 8,
  },
  {
    name: "Anti-Streptolysin O (ASO) Titre",
    short_code: "ASO",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "<200 (adult) / <150 (child <5 yr)",
    unit: "IU/mL",
    price: 250,
    turnaround_hrs: 6,
  },
  {
    name: "IgA (Immunoglobulin A)",
    short_code: "IGA",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "70–400",
    unit: "mg/dL",
    price: 600,
    turnaround_hrs: 8,
  },
  {
    name: "IgG (Immunoglobulin G)",
    short_code: "IGG",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "700–1600",
    unit: "mg/dL",
    price: 600,
    turnaround_hrs: 8,
  },
  {
    name: "IgM (Immunoglobulin M)",
    short_code: "IGM",
    category: "Immunology",
    sample_type: "Serum",
    reference_range: "40–230",
    unit: "mg/dL",
    price: 600,
    turnaround_hrs: 8,
  },

  // ══════════════════════════════════════════════════════════════
  // PANCREATIC / DIABETES-RELATED
  // ══════════════════════════════════════════════════════════════
  {
    name: "Serum Amylase (Pancreatic)",
    short_code: "P-AMY",
    category: "Pancreatic",
    sample_type: "Serum",
    reference_range: "13–53",
    unit: "U/L",
    price: 350,
    turnaround_hrs: 4,
  },

  // ══════════════════════════════════════════════════════════════
  // BLOOD GASES / ABG (in-patient/ICU)
  // ══════════════════════════════════════════════════════════════
  {
    name: "Arterial Blood Gas (ABG)",
    short_code: "ABG",
    category: "Blood Gases",
    sample_type: "Arterial blood (heparinised syringe, on ice)",
    reference_range: "pH 7.35–7.45 / PaCO₂ 35–45 / PaO₂ 80–100 / HCO₃ 22–26 / SpO₂ 95–100%",
    unit: "Panel",
    price: 800,
    turnaround_hrs: 1,
  },

  // ══════════════════════════════════════════════════════════════
  // MICROBIOLOGY
  // ══════════════════════════════════════════════════════════════
  {
    name: "Blood Culture and Sensitivity",
    short_code: "BCS",
    category: "Microbiology",
    sample_type: "Blood (aerobic + anaerobic bottles, 2 sets)",
    reference_range: "No growth",
    unit: "Qualitative",
    price: 1200,
    turnaround_hrs: 72,
  },
  {
    name: "Sputum Culture and Sensitivity",
    short_code: "SPCS",
    category: "Microbiology",
    sample_type: "Sputum (early morning, deep cough)",
    reference_range: "No significant growth",
    unit: "Qualitative",
    price: 600,
    turnaround_hrs: 72,
  },
  {
    name: "Stool Routine Examination",
    short_code: "SRE",
    category: "Microbiology",
    sample_type: "Fresh stool (within 30 min of collection)",
    reference_range: "No ova/cysts/parasites / No pus cells / No blood",
    unit: "Qualitative",
    price: 120,
    turnaround_hrs: 4,
  },
  {
    name: "Stool Culture and Sensitivity",
    short_code: "SCS",
    category: "Microbiology",
    sample_type: "Fresh stool",
    reference_range: "No pathogenic organisms",
    unit: "Qualitative",
    price: 500,
    turnaround_hrs: 72,
  },
  {
    name: "Throat Swab Culture",
    short_code: "TSC",
    category: "Microbiology",
    sample_type: "Throat swab",
    reference_range: "Normal flora / No pathogen",
    unit: "Qualitative",
    price: 500,
    turnaround_hrs: 48,
  },
  {
    name: "KOH Mount (Fungal)",
    short_code: "KOH",
    category: "Microbiology",
    sample_type: "Skin scraping / hair / nail",
    reference_range: "No fungal elements seen",
    unit: "Qualitative",
    price: 200,
    turnaround_hrs: 4,
  },
  {
    name: "Gram Stain",
    short_code: "GRAM",
    category: "Microbiology",
    sample_type: "Clinical specimen (pus/fluid/sputum)",
    reference_range: "No organisms seen",
    unit: "Qualitative",
    price: 150,
    turnaround_hrs: 2,
  },
  {
    name: "AFB Stain (Acid Fast Bacilli / TB)",
    short_code: "AFB",
    category: "Microbiology",
    sample_type: "Sputum / BAL / other specimen",
    reference_range: "No AFB seen",
    unit: "Qualitative / Grade",
    price: 200,
    turnaround_hrs: 4,
  },
];
